ignore_colors = [
    #000000, # filter all black, DO NOT USE "#"!!!
]
width = 1000
height = 1000
add-x = 500
add-y = 500

default_prio = 120 # priority: higher number = higher chance of being placed


# example:
# [[structure]]
# name = "flagge-ost"
# file = "flagge-ost.png"
# priority_file = "flagge-ost_prio.png"
# startx = 1332
# starty = 1122
# priority = 127

[[structure]]
name = "jules_pikachu"
file = "jules_pikachu.png"
startx = -7
starty = -435
priority = 127

[[structure]]
name = "ottifant"
file = "ottifant.png"
startx = 344
starty = -448
priority = 127

[[structure]]
name = "paragraf_eins"
file = "paragraf_eins.png"
startx = 170
starty = -450
priority = 127

[[structure]]
name = "spezi"
file = "spezi.png"
startx = 300
starty = -450
priority = 127

[[structure]]
name = "TUEV"
file = "TUEV.png"
startx = -400
starty = -450
priority = 127

[[structure]]
name = "JojoCroc"
file = "JojoCroc.png"
startx = 125
starty = -450
priority = 127

[[structure]]
name = "subredditstra"
file = "subredditstra.png"
startx = -499
starty = -420
priority = 127

[[structure]]
name = "getraenke"
file = "getraenke.png"
startx = -280
starty = -448
priority = 127

[[structure]]
name = "leibniz_keks"
file = "leibniz_keks.png"
startx = 50
starty = -448
priority = 127

[[structure]]
name = "ketchup"
file = "ketchup.png"
startx = 269
starty = -441
priority = 127

[[structure]]
name = "pombaer"
file = "pombaer.png"
startx = 89
starty = -437
priority = 127

[[structure]]
name = "berliner"
file = "berliner.png"
startx = 51
starty = -424
priority = 127

[[structure]]
name = "nospeed"
file = "nospeed.png"
startx = -20
starty = -449
priority = 127

[[structure]]
name = "muenzen"
file = "muenzen.png"
startx = -344
starty = -449
priority = 127

[[structure]]
name = "kippfenster"
file = "kippfenster.png"
startx = -426
starty = -432
priority = 127

[[structure]]
name = "spezhs"
file = "spezhs.png"
startx = -140
starty = -450
priority = 127

[[structure]]
name = "euro10"
file = "euro10.png"
startx = -339
starty = -419
priority = 127

[[structure]]
name = "euro20"
file = "euro20.png"
startx = -339
starty = -439
priority = 127
